package com.lolzteam.api.runtime

import kotlinx.serialization.DeserializationStrategy
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.SerialKind
import kotlinx.serialization.descriptors.StructureKind
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

/**
 * Decodes a [JsonElement] into [T] with lenient type coercion.
 *
 * The Lolzteam API sometimes returns inconsistent types for the same field
 * (e.g. empty array `[]` instead of an object, or a string `"none"` instead
 * of a number). This function walks the [SerialDescriptor] tree alongside the
 * JSON tree and coerces mismatched node types to safe defaults before handing
 * the result to the normal [Json.decodeFromJsonElement].
 */
@OptIn(ExperimentalSerializationApi::class)
internal fun <T> Json.lenientDecodeFromJsonElement(
    deserializer: DeserializationStrategy<T>,
    element: JsonElement,
): T {
    val coerced = coerceElement(deserializer.descriptor, element)
    return decodeFromJsonElement(deserializer, coerced)
}

@OptIn(ExperimentalSerializationApi::class)
private fun coerceElement(
    descriptor: SerialDescriptor,
    element: JsonElement,
): JsonElement {
    // Unwrap nullable descriptors — the actual content descriptor is at index 0
    if (descriptor.isNullable && element is JsonNull) return JsonNull
    val inner =
        if (descriptor.serialName == "kotlinx.serialization.Nullable") {
            // For nullable wrappers generated by kotlinx.serialization, the real
            // descriptor lives at getElementDescriptor(0).
            descriptor.getElementDescriptor(0)
        } else {
            descriptor
        }

    return when {
        // JsonElement / JsonObject / JsonArray / JsonPrimitive — accept anything
        inner.serialName.startsWith("kotlinx.serialization.json.Json") -> element

        // StringOrInt — accept anything primitive-ish
        inner.serialName == "StringOrInt" -> element

        // ── Structures ──────────────────────────────────────────────
        inner.kind == StructureKind.CLASS || inner.kind == StructureKind.OBJECT -> {
            coerceToObject(inner, element)
        }

        inner.kind == StructureKind.LIST -> {
            coerceToList(inner, element)
        }

        inner.kind == StructureKind.MAP -> {
            coerceToMap(inner, element)
        }

        // ── Primitives ──────────────────────────────────────────────
        inner.kind is PrimitiveKind -> {
            coerceToPrimitive(inner.kind as PrimitiveKind, element)
        }

        // ── Enums ───────────────────────────────────────────────────
        inner.kind == SerialKind.ENUM -> {
            if (element is JsonPrimitive) element else JsonPrimitive("")
        }

        else -> element
    }
}

@OptIn(ExperimentalSerializationApi::class)
private fun coerceToObject(
    descriptor: SerialDescriptor,
    element: JsonElement,
): JsonElement {
    if (element !is JsonObject) {
        // API returned [] or a primitive where an object was expected → empty object
        // so that decodeFromJsonElement falls back to default values for all properties.
        return JsonObject(emptyMap())
    }
    // Recursively coerce each known property
    val nameToIndex =
        buildMap {
            for (i in 0 until descriptor.elementsCount) {
                put(descriptor.getElementName(i), i)
            }
        }
    val result = mutableMapOf<String, JsonElement>()
    for ((key, value) in element) {
        val idx = nameToIndex[key]
        if (idx != null) {
            result[key] = coerceElement(descriptor.getElementDescriptor(idx), value)
        } else {
            result[key] = value // unknown keys are kept as-is (ignoreUnknownKeys handles them)
        }
    }
    return JsonObject(result)
}

@OptIn(ExperimentalSerializationApi::class)
private fun coerceToList(
    descriptor: SerialDescriptor,
    element: JsonElement,
): JsonElement {
    if (element !is JsonArray) {
        // API returned an object or primitive where an array was expected
        return JsonArray(emptyList())
    }
    // The element descriptor for list items is at index 0
    if (descriptor.elementsCount == 0) return element
    val itemDescriptor = descriptor.getElementDescriptor(0)
    val coerced = element.map { coerceElement(itemDescriptor, it) }
    return JsonArray(coerced)
}

@OptIn(ExperimentalSerializationApi::class)
private fun coerceToMap(
    descriptor: SerialDescriptor,
    element: JsonElement,
): JsonElement {
    if (element !is JsonObject) return JsonObject(emptyMap())
    if (descriptor.elementsCount < 2) return element
    val valueDescriptor = descriptor.getElementDescriptor(1)
    val result = mutableMapOf<String, JsonElement>()
    for ((key, value) in element) {
        result[key] = coerceElement(valueDescriptor, value)
    }
    return JsonObject(result)
}

private fun coerceToPrimitive(
    kind: PrimitiveKind,
    element: JsonElement,
): JsonElement {
    if (element is JsonPrimitive) {
        // Handle number fields receiving non-numeric strings like "none"
        if (kind == PrimitiveKind.DOUBLE || kind == PrimitiveKind.FLOAT ||
            kind == PrimitiveKind.INT || kind == PrimitiveKind.LONG ||
            kind == PrimitiveKind.SHORT || kind == PrimitiveKind.BYTE
        ) {
            if (!element.isString) return element
            // Try parsing as a number; if it fails, return 0
            val content = element.content
            if (content.toDoubleOrNull() != null) return element
            return JsonPrimitive(0)
        }
        return element
    }
    // Non-primitive where a primitive was expected → return a safe default
    return when (kind) {
        PrimitiveKind.STRING -> JsonPrimitive("")
        PrimitiveKind.BOOLEAN -> JsonPrimitive(false)
        PrimitiveKind.DOUBLE, PrimitiveKind.FLOAT -> JsonPrimitive(0.0)
        PrimitiveKind.INT, PrimitiveKind.LONG, PrimitiveKind.SHORT, PrimitiveKind.BYTE -> JsonPrimitive(0)
        PrimitiveKind.CHAR -> JsonPrimitive("")
    }
}
